### ISSUE TITLE
No XML files in target/allure-results folder afterrunning tests via mvn clean test

### ISSUE THREAD

**Issue by AruslanK** [allure-framework/allure-maven-plugin#12]
Hi,
I have maven-testng-allure project . Allure-report  integration was done according to example. The problem is that no XML files are generated after executing tests via "mvn clean test" command. But, in case if test execution was made via TestNG (in Eclipse: Run as TestNG suit) everything is OK. What problem could cause such behaviour?

**Comment by vania-pooh** [comment]
The most common configuration issues are:
1) Missing maven-surefire-plugin configuration like the [following](https://github.com/allure-examples/allure-testng-example/blob/master/pom.xml#L52-L68) and respective AspectJ configuration
2) Missing Allure TestNG dependency: https://github.com/allure-examples/allure-testng-example/blob/master/pom.xml#L52-L68 This one adds AllureAdapter class which is automatically loaded by TestNG via SPI. Please check that test listeners are not disabled in your TestNG config.

**Comment by AruslanK** [comment]
Thanks for quick reply,  
I have re-checked my pom.xml, and seems that it has all mentioned dependencies. Please take a look:
   <properties>
        <allure.version>1.4.13</allure.version>
        <aspectj.version>1.8.5</aspectj.version>
         
    </properties>
    
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                
                <configuration>
                    
                    <suiteXmlFiles>
                        <suiteXmlFile>testng.xml</suiteXmlFile>
                    </suiteXmlFiles>
                                                  	
                    <testFailureIgnore>true</testFailureIgnore>
                    <argLine>
                        -javaagent:${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
                    </argLine>
                </configuration>
               
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>                                	
                
            </plugin>
            
                        
         </plugins>
    </build>
    
    
    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven-plugin</artifactId>
                <version>2.2</version>
            </plugin>
        </plugins>
    </reporting>  

    <dependencies>
    
    	<dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-testng-adaptor</artifactId>
            <version>${allure.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
<dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.1.1</version>
            <scope>test</scope>
        </dependency>
</dependencies>
Looks like I have add everything, but I will wait for your advice. Thanks one more time.

**Comment by baev** [comment]
@AruslanK seems like your configuration is correct. Does `allure-testng-example` work for you? Could you provide simple project to reproduce the problem?

**Comment by AruslanK** [comment]
Hi Dmitry,
*--"Does allure-testng-example work for you?"*
This example I haven't try yet, just used it as FAQ, but I think I will do
it on weekends.
*--"Could you provide simple project to reproduce the problem?"*
Please find attached archive below. I think it will be rather simple.

On Fri, May 22, 2015 at 1:12 PM, Dmitry Baev <notifications@github.com>
wrote:

> @AruslanK <https://github.com/AruslanK> seems like your configuration is
> correct. Does allure-testng-example work for you? Could you provide
> simple project to reproduce the problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/allure-framework/allure-maven-plugin/issues/12#issuecomment-104608224>
> .
>



-- 
Best regards,

*Ruslan Kryvosheiev*
GlobalLogic
*Skype: shaman2804*

**Comment by AruslanK** [comment]
Seems like attachment won't be added. If so, kindly please clone my repo with porject from: https://github.com/AruslanK/test1.git

**Comment by baev** [comment]
@AruslanK problem with your testNg version. Use testNg `6.8` or higher. *Note: allure-testng-adaptor already depends on testng*. The following configuration will works for you:

```xml
    <dependencies>
        <dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-testng-adaptor</artifactId>
            <version>${allure.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>junit</groupId>
                    <artifactId>junit</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
```

**Comment by AruslanK** [comment]
Yes, that's work. 
Thanks.
