### ISSUE TITLE
Provider ru.yandex.qatools.allure.testng.AllureTestListener not found when using testNG 6.9.4

### ISSUE THREAD

**Issue by SpyderWeiss** [allure-framework/allure-maven-plugin#13]
If I run tests under TestNG 6.8.21 with Allure Maven Plugin 2.2 and Allure version 1.4.14, it works great, if I update to version 6.9.4 of TestNG, I get the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project Automation: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
[ERROR] java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider ru.yandex.qatools.allure.testng.AllureTestListener not found
[ERROR] at java.util.ServiceLoader.fail(ServiceLoader.java:231)
[ERROR] at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
[ERROR] at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:365)
[ERROR] at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
[ERROR] at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:945)
[ERROR] at org.testng.TestNG.initializeConfiguration(TestNG.java:895)
[ERROR] at org.testng.TestNG.run(TestNG.java:1006)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
[ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] -> [Help 1]
```

**Comment by baev** [comment]
@SpyderWeiss thanks for the suggestion! 

The problem on TestNg side. See https://groups.google.com/forum/#!topic/testng-users/-fHtyj6EpLI 

@cbeust promises to release `6.9.5` with fixes soon.

**Comment by baev** [comment]
TestNg 6.9.5 was released, bug should be fixed.

**Comment by yashpandey** [comment]
I am running my test with maven version 2.20 and Allure . I am getting this error while running the test with mvn clean test

[ERROR] org.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] org.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:665)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
yash.pandey@yashpandey-laptop:~/iPlexus-ui/iPlexus$  org.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated
org.testng.ITestNGListener:: command not found

**Comment by baev** [comment]
@yashpandey that is not an Allure issue, seems like problem with your classpath.

**Comment by artur-fnbtech** [comment]
`Could not resolve dependencies for project com.<CompanyName>:jar:0.0.1-SNAPSHOT: Failure to find io.qameta.allure:allure-testng:jar:LAST_VERSION in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
`

we use testng 6.11

**Comment by Sonal-Katre** [comment]
i am using testng version-7.8.0 still i am getting error-
java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider APIFramework.src.test.java.util.CucumberTestNgFilter.java not found
