### ISSUE TITLE
Report not working on other browsers than Firefox

### ISSUE THREAD

**Issue by CosminGramada** [allure-framework/allure-maven-plugin#20]
Hi,

It seems that the report is displayed properly and working fine only on Firefox.
However if I try opening it on Chrome (46.0.2490.71 m) or Edge (20.10240.16384.0) the "Your report seems to be broken" message is displayed.
E.g. 
~/target/site/allure-maven-plugin/index.html#/home is displaying 

Message: {{error.status}}

Debug: {{error}}

Let me know if additional details are needed.

Good job with the framework, it;s a life-saver and hoping to see it working on Chrome at least, as Firefox is only used for testing purposes.

Cosmin

**Comment by baev** [comment]
@CosminGramada thanks for suggestion.

See http://stackoverflow.com/questions/23997449/allure-report-nothing-shown-in-chrome
