### ISSUE TITLE
Unable to generate allure report using allure maven plugin getting "Results directory for module Cloudbrowse tests not found"

### ISSUE THREAD

**Issue by prasad417** [allure-framework/allure-maven-plugin#25]
Hi,

I am overriding the allure.results.directory and allure.report.directory but I am unable to generate allure report

Below is the error  I am getting

[DEBUG] Configuring mojo ru.yandex.qatools.allure:allure-maven-plugin:2.5:bulk from plugin realm ClassRealm[plugin>ru.yandex.qatools.allure:allure-maven-plugin:2.5, parent: ClassRealm[plugin>org.apache.maven.plugins:maven-site-plugin:3.3, parent: sun.misc.Launcher$AppClassLoader@5c647e05]]
[DEBUG] Configuring mojo 'ru.yandex.qatools.allure:allure-maven-plugin:2.5:bulk' with basic configurator -->
[DEBUG]   (f) resultsDirectory = target/16-21/allure-results_2016_05_19_02_56_AM
[DEBUG]   (f) inputDirectories = target/16-21/allure-results_2016_05_19_02_56_AM
[DEBUG]   (f) reportDirectory = target/16-21/allure-results_2016_05_19_02_56_AM/allure-report
[DEBUG]   (f) reportingOutputDirectory = target/16-21/allure-results_2016_05_19_02_56_AM/allure-report
[DEBUG]   (f) allureMain = ru.yandex.qatools.allure.AllureMain
[DEBUG]   (f) buildDirectory = /Users/a6001074/BBY_Cloudbrowse/target
[DEBUG]   (f) project = MavenProject: com.bby:BBY_Cloudbrowse:0.0.1-SNAPSHOT @ /Users/a6001074/BBY_Cloudbrowse/pom.xml
[DEBUG]   (f) projectRepositories = [central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG]   (f) propertiesFilePath = report.properties
[DEBUG]   (f) repositorySession = org.eclipse.aether.DefaultRepositorySystemSession@28369db0
[DEBUG]   (f) version = 1.4.23
[DEBUG]   (f) pluginDescriptor = Component Descriptor: role: 'org.apache.maven.plugin.Mojo', implementation: 'ru.yandex.qatools.allure.report.AlureAggregateMojo', role hint: 'ru.yandex.qatools.allure:allure-maven-plugin:2.5:aggregate'
role: 'org.apache.maven.plugin.Mojo', implementation: 'ru.yandex.qatools.allure.report.AllureReportMojo', role hint: 'ru.yandex.qatools.allure:allure-maven-plugin:2.5:report'
role: 'org.apache.maven.plugin.Mojo', implementation: 'ru.yandex.qatools.allure.report.HelpMojo', role hint: 'ru.yandex.qatools.allure:allure-maven-plugin:2.5:help'
role: 'org.apache.maven.plugin.Mojo', implementation: 'ru.yandex.qatools.allure.report.AllureBulkMojo', role hint: 'ru.yandex.qatools.allure:allure-maven-plugin:2.5:bulk'
---
[DEBUG] -- end configuration --
[DEBUG] Mapped url: /Users/a6001074/BBY_Cloudbrowse/src/site to relative path: src/site
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Skipped "Allure" report, file "allure-maven-plugin.html" already exists for the English version.
[INFO] Skipped "Allure" report, file "allure-maven-plugin.html" already exists for the English version.
[DEBUG] Generating /Users/a6001074/BBY_Cloudbrowse/target/site/allure-maven-plugin.html
[INFO] Generating "Allure" report    --- allure-maven-plugin:2.5
[INFO] Generate Allure report (aggregate) with version 1.4.23
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=36, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=29, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=1, ConflictResolver.conflictItemCount=36, DefaultDependencyCollector.collectTime=29, DefaultDependencyCollector.transformTime=1}
[DEBUG] Found 29 dependencies for Dependency {groupId=ru.yandex.qatools.allure, artifactId=allure-bundle, version=1.4.23, type=jar}
[DEBUG] ru.yandex.qatools.allure:allure-bundle:1.4.23
[DEBUG] org.slf4j:slf4j-simple:1.7.12
[DEBUG] org.slf4j:slf4j-api:1.7.12
[DEBUG] ru.yandex.qatools.allure:allure-report-data:1.4.23
[DEBUG] ru.yandex.qatools.allure:allure-report-plugin-api:1.4.23
[DEBUG] ru.yandex.qatools.allure:allure-model:1.4.23
[DEBUG] org.jvnet.jaxb2_commons:jaxb2-basics-runtime:0.9.3
[DEBUG] ru.yandex.qatools.properties:properties-loader:1.5
[DEBUG] commons-beanutils:commons-beanutils-core:1.8.3
[DEBUG] commons-logging:commons-logging:1.1.1
[DEBUG] com.google.inject:guice:4.0
[DEBUG] javax.inject:javax.inject:1
[DEBUG] aopalliance:aopalliance:1.0
[DEBUG] ru.yandex.qatools.allure:allure-commons:1.4.23
[DEBUG] commons-io:commons-io:2.4
[DEBUG] com.fasterxml.jackson.core:jackson-databind:2.3.0
[DEBUG] com.fasterxml.jackson.core:jackson-annotations:2.3.0
[DEBUG] com.fasterxml.jackson.core:jackson-core:2.3.0
[DEBUG] com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.3.0
[DEBUG] org.pegdown:pegdown:1.4.2
[DEBUG] org.parboiled:parboiled-java:1.1.6
[DEBUG] org.parboiled:parboiled-core:1.1.6
[DEBUG] org.ow2.asm:asm:4.1
[DEBUG] org.ow2.asm:asm-tree:4.1
[DEBUG] org.ow2.asm:asm-analysis:4.1
[DEBUG] org.ow2.asm:asm-util:4.1
[DEBUG] org.modelmapper:modelmapper:0.7.3
[DEBUG] org.codehaus.groovy:groovy:2.4.3
[DEBUG] com.google.guava:guava:18.0
[INFO] Generate Allure report to target/16-21/allure-results_2016_05_19_02_56_AM/allure-report
[WARNING] Results directory for module Cloudbrowse tests not found.
[WARNING] Allure report was skipped because there is no results directories found.
[DEBUG] Multipage report: 0 subreports

**Comment by prasad417** [comment]
Here is my POM.xml

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<testng.version>6.9.10</testng.version>
		<selenium.version>2.53.0</selenium.version>
		<chromedriver.version>2.53.0</chromedriver.version>
		<safaridriver.version>2.53.0</safaridriver.version>
		<webdrivermanager.version>1.4.3</webdrivermanager.version>
		<mavensurefire.version>2.19</mavensurefire.version>
		<mavencompiler.version>3.5.1</mavencompiler.version>
		<mavensurefirereport.version>2.19</mavensurefirereport.version>
		<allure.version>1.4.23</allure.version>
		<aspectj.version>1.8.9</aspectj.version>
		<alluremaven.version>2.5</alluremaven.version>
		<mavenantrun.version>1.8</mavenantrun.version>
		<timestamp>${maven.build.timestamp}</timestamp>
		<maven.build.timestamp.format>yyyy_MM_dd_hh_mm_a</maven.build.timestamp.format>
		<release.number>16-21</release.number>
		<allure.results.directory>target/${release.number}/allure-results_${timestamp}</allure.results.directory>
		<allure.report.directory>target/${release.number}/allure-results_${timestamp}/allure-report</allure.report.directory>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${testng.version}</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-server</artifactId>
			<version>${selenium.version}</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-chrome-driver</artifactId>
			<version>${chromedriver.version}</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-safari-driver</artifactId>
			<version>${safaridriver.version}</version>
		</dependency>
		<dependency>
			<groupId>ru.yandex.qatools.allure</groupId>
			<artifactId>allure-testng-adaptor</artifactId>
			<version>${allure.version}</version>
		</dependency>
		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>${webdrivermanager.version}</version>
		</dependency>
	</dependencies>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-antrun-plugin</artifactId>
					<version>${mavenantrun.version}</version>
					<executions>
						<execution>
							<id>create</id>
							<phase>compile</phase>
							<configuration>
								<target>
									<echo>Creating directory</echo>
									<mkdir dir="${allure.results.directory}" />
								</target>

							</configuration>
							<goals>
								<goal>run</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${mavensurefire.version}</version>
					<configuration>
						<suiteXmlFiles>
							<suiteXmlFile>src/test/resources/regressionConfig.xml</suiteXmlFile>
						</suiteXmlFiles>
						<testFailureIgnore>false</testFailureIgnore>
						<argLine>
							-javaagent:${HOME}/.m2/repository/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
						</argLine>
						<systemProperties>
							<property>
								<name>allure.results.directory</name>
								<value>${allure.results.directory}</value>
								<name>allure.report.directory</name> 
								<value>${allure.report.directory}</value>
							</property>
						</systemProperties>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>org.aspectj</groupId>
							<artifactId>aspectjweaver</artifactId>
							<version>${aspectj.version}</version>
						</dependency>
					</dependencies>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${mavencompiler.version}</version>
					<configuration>
						<source>1.7</source>
						<target>1.7</target>
					</configuration>
				</plugin>

			</plugins>
		</pluginManagement>
	</build>

	<reporting>
		<excludeDefaults>true</excludeDefaults>
		<plugins>
			<plugin>
				<groupId>ru.yandex.qatools.allure</groupId>
				<artifactId>allure-maven-plugin</artifactId>
				<version>${alluremaven.version}</version>
				<configuration>
					<resultsDirectory>${allure.results.directory}</resultsDirectory>
					<inputDirectories>${allure.results.directory}</inputDirectories>
					<reportDirectory>${allure.report.directory}</reportDirectory>
					<reportingOutputDirectory>${allure.report.directory}</reportingOutputDirectory>
					<failReportIfEmpty>false</failReportIfEmpty>
				</configuration>
			</plugin>
		</plugins>
	</reporting>

**Comment by lanwen** [comment]
did you try to use direct goal `report`?
```xml
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven-plugin</artifactId>
                <version>2.5</version>

                <reportSets>
                    <reportSet>
                        <reports>
                            <report>report</report>
                        </reports>
                    </reportSet>
                </reportSets>
```

**Comment by prasad417** [comment]
Hi Ianwen,

Thanks for the reply. I figured out with the below configuration it is working

resultsDirectory set to "${release.number}/allure-results_${timestamp}"
inputDirectories set to "${release.number}/allure-results_${timestamp}"

**Comment by prasad417** [comment]
We can close this issue.
