### ISSUE TITLE
logback pattern is unsupported in allure-maven-plugin

### ISSUE THREAD

**Issue by p00j4** [allure-framework/allure-maven-plugin#3]
After adding allure in pom, my original logger pattern is not reflecting in loggers in console
I'm having 
```
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>[%5p] [%t] %m [%M::%F:%L] %n</pattern>
		</encoder>
	</appender>
```

which gives logs like this: 
``` 
[INFO] [main] TC-1234612:Determining By locator for: id=cal [createObject::Resolver.java:87]] 
```

But after adding allure dependency, logger comes like- 
```
15:56:48.018 [main] INFO  com.domain.qa.fw.util.Resolver - TC-1234612:Determining By locator for: id=cal 
```

What is the work around to get back my logger pattern !

**Comment by baev** [comment]
Logging in maven plugin fixed via #10 

Related issue for logging for adapters https://github.com/allure-framework/allure-core/issues/564
