### ISSUE TITLE
Steps and attachments no longer display in the xUnit or Defects section

### ISSUE THREAD

**Issue by crazycabo** [allure-framework/allure-maven-plugin#7]
Unless a change has been made I am unaware of, steps and attachments no longer display in the xUnit section when viewing individual test results. All other sections including Behaviors and Timeline display as normal toward the bottom of the results window, but not xUnit or Defects
![screen shot 2015-03-12 at 6 34 12 pm](https://cloud.githubusercontent.com/assets/1331085/6629631/85b976a0-c8e6-11e4-8a1c-2c9d6b007659.png)
![screen shot 2015-03-12 at 6 34 36 pm](https://cloud.githubusercontent.com/assets/1331085/6629634/8cb06356-c8e6-11e4-8a43-c231daa167a3.png)
![screen shot 2015-03-12 at 6 34 49 pm](https://cloud.githubusercontent.com/assets/1331085/6629638/985a6580-c8e6-11e4-9e13-c59178a2fe36.png)
![screen shot 2015-03-12 at 6 35 00 pm](https://cloud.githubusercontent.com/assets/1331085/6629639/9b37c3f6-c8e6-11e4-86ee-d09e058e687c.png)

**Comment by baev** [comment]
@crazycabo sorry for long delay. It's still relevant?

**Comment by crazycabo** [comment]
No, it is not.
